# Convolução

In [1]:
import torch
from torch import nn
import torch.nn.functional as F

x = torch.tensor([5, 4, 8, 7, 9, 3, 6], dtype=torch.float32)
weight = torch.tensor([1, 2, 3], dtype=torch.float32)
kernel_size = len(weight)
# Adiciona dimensão do batch e canal
x = x.reshape(1, 1, len(x))
weight = weight.reshape(1, 1, len(weight))

y = F.conv1d(x, weight, padding=kernel_size//2)
y

ModuleNotFoundError: No module named 'torch'

In [18]:
conv = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=kernel_size, padding=kernel_size//2, bias=False)

with torch.no_grad():
    conv.weight[:] = weight

conv(x)

tensor([[[22., 37., 41., 49., 34., 33., 15.]]], grad_fn=<ConvolutionBackward0>)

## Uma convolução pode ser implementada como um produto matricial

In [21]:
matrix = torch.tensor([
    [2, 3, 0, 0, 0, 0, 0],
    [1, 2, 3, 0, 0, 0, 0],
    [0, 1, 2, 3, 0, 0, 0],
    [0, 0, 1, 2, 3, 0, 0],
    [0, 0, 0, 1, 2, 3, 0],
    [0, 0, 0, 0, 1, 2, 3],
    [0, 0, 0, 0, 0, 1, 2],
], dtype=torch.float32)
x = torch.tensor([5, 4, 8, 7, 9, 3, 6], dtype=torch.float32)
F.linear(x, matrix)

tensor([22., 37., 41., 49., 34., 33., 15.])

## Convolução com mais de um canal

In [25]:
x = torch.rand(size=(1, 4, 7))
conv = nn.Conv1d(in_channels=4, out_channels=256, kernel_size=kernel_size, padding=kernel_size//2, bias=False)
y = conv(x)
y.shape

torch.Size([1, 256, 7])

Em uma camada de convolução:

- O número de canais de saída define o número de filtros da camada
- Cada filtro possui tamanho espacial `kernel_size`
- Cada filtro possui profundidade (número de canais) igual ao tensor de entrada

In [28]:
conv.weight.shape

torch.Size([256, 4, 3])

## Stride

O stride define o passo do filtro

In [32]:
x = torch.tensor([5, 4, 8, 7, 9, 3, 6], dtype=torch.float32)
weight = torch.tensor([1, 2, 3], dtype=torch.float32)
kernel_size = len(weight)
# Adiciona dimensão do batch e canal
x = x.reshape(1, 1, len(x))
weight = weight.reshape(1, 1, len(weight))

y = F.conv1d(x, weight, stride=2)
y

tensor([[[37., 49., 33.]]])

## Dilatação

In [34]:
y = F.conv1d(x, weight, dilation=2)
y

tensor([[[48., 27., 44.]]])